CREATE TABLE Users(user_id VARCHAR(5),password VARCHAR(10),role VARCHAR(5));
DROP TABLE Users;
INSERT INTO Users VALUES('admin','root','admin');
SELECT * FROM Users;

INSERT INTO LOANPROGRAMSOFFERED VALUES ('def','gdfhgsah','ghhshsg',20,100,10000,10,'jfdbsj');
SELECT * FROM LOANAPPLICATION;
SELECT * FROM APPROVEDLOANS;
